version: '3.7'
services:
  web:
    image: 'nginx:latest'
    restart: always
    volumes:
      - './images/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
      - './images/nginx/logs:/var/logs/nginx'
    ports:
      - '80:80'
  app:
    build: './images/app'
    working_dir: '/app'
    volumes:
      - '../app:/app'
      - './images/app/logs/php-fpm:/usr/local/var/log/php'
  db:
    image: 'mariadb:latest'
    restart: 'always'
    volumes:
      - 'testovoe-db:/var/lib/mysql'
    environment:
      - 'MYSQL_DATABASE=db'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=rootpassword'
    ports:
      - '3306:3306'
volumes:
  testovoe-db: